on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - name: build site
        run: npm install @11ty/eleventy
        run: npx @11ty/eleventy
        run: echo Build complete! Deploying...

      - name: deploy2nekoweb
        uses: https://github.com/indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'funkylevi.nekoweb.org'
          nekoweb-username: 'funkylevi'
          directory: '_site'
      - run: echo Deployment Completed!