on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - run: npm install @11ty/eleventy
      - run: npx @11ty/eleventy
      - run: echo Build complete! Deploying...
      - uses: https://codeberg.org/git-pages/action@v2
        with:
          site: "https://${{ forge.repository_owner }}.pages.gay/"
          token: ${{ forge.token }}
          source: _site/
      - run: Deployment Completed!