# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: gitea
  repo: funkylevi/webbed-site
  base_url: https://git.gay/
  api_root: https://git.gay/api/v1
  app_id: 00e2b9e3-bd6c-4b94-9ba5-6283c26b4831

media_folder: /assets
public_folder: /

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /blog/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }